[package]
name = "rsdlp"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
panic = "abort"
opt-level = 3
strip = "debuginfo"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "sync", "time"] }
tokio-util = { version = "0.7", features = ["io"] }
axum = { version = "0.8", features = ["default", "macros"] }
libc = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
grammers-client = "0.8"
grammers-session = "0.8"
grammers-mtsender = "0.8"
sqlite = "0.37"
bcrypt = "0.17"
